language: cpp
compiler: clang


before_script:
  - sudo apt-get install libboost-test-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libspdlog-dev -y
  - sudo apt-get install doxygen
  - sudo apt-get upgrade
script:
  - doxygen ./Doxyfile
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN  # 
    keep-history: true
    local-dir: DoxygenOutput/html/
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      - curl -T bulk-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -urejdok:$BINTRAY_API_KEY "https://api.bintray.com/content/rejdok/OTUS/bulk/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"


